project_id = "ffhnameizeueevuqvjfi"

[functions.send-order-confirmation]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.guest-checkout]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.send-sms-otp]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.newsletter-unsubscribe]
verify_jwt = false
